#!/usr/bin/env bash
# Transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
# checks that the script is being called
# with the correct number of arguments.
# If not, it prints an error message and exits the script.

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
# uses the scp command to transfer the file at $1 to the server with IP address $2,
# using the username $3 and the SSH private key located at $4.
# The file is transferred to the remote user's home directory ~/
# and Strict host key checking is disabled.
