#!/usr/bin/env bash
# Nginx server redirects to another page

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    location /redirect_me {
        return 301 http://mcdatadev.tech/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
