#!/usr/bin/env bash
# Nginx error 404 page

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html /etc/nginx/html/404.html

echo "Hello World!" > /etc/nginx/html/index.html
# Configure 404 page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    location /redirect_me {
        return 301 http://mcdatadev.tech/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
