#!/usr/bin/env bash
# Backing up database and compressing to a tar.gz archive
PASSWORD="shnarf"
mysqldump -uroot -p"${PASSWORD}" --all-databases > backup.sql
echo 'shnarf'
gzip -c backup.sql > "$(date +"%d-%m-%Y").tar.gz"
