#!/usr/bin/env bash
# from 1-10 displays bad luck for the 4th loop, displays good luck for the 8th loop iteration, displays Best School for the other iterations
i=0
while [ $i -le 9 ]
do
    if (($i == 3))
    then
        echo "bad luck"
    elif (($i == 7))
    then 
        echo "good luck"
    else 
        echo "Best School"
    fi
    (($i++))
done
