#!/usr/bin/env bash
# feeling lucky?
i=0
while [ $i -le 19 ]
do
    echo "$i"
    case $i in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    i=$((i++))    
done