#!/usr/bin/env bash
# does file school exist? if yes, display
if [ -e school ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school is not empty"
	else
		echo "school is empty"
	fi
	if [ -f school ]
	then
		echo "school is a regular file"
	fi
else
	echo "school  does not exist"
fi
