#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
sudo apt-get update
sudo apt-get -y install haproxy
sudo chown -R $USER:$USER /etc/haproxy
sudo echo "
frontend http_front
  bind *:80
  mode http
  default_backend http_back
backend http_back
   balance roundrobin
   server 5541-web-01 15.237.150.77 check
   server 5541-web-02 13.38.20.126 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
