#!/usr/bin/env bash
#Install HAproxy server
sudo apt-get -y update
sudo apt-get -y upgrade
apt install -y haproxy
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
mkdir -p /etc/haproxy
touch /etc/haproxy/haproxy.cfg
echo "
    defaults
    mode http
    timeout client 10s
    timeout server 10s
    timeout connect 5s
    timeout http-request 10s
frontend web-frontend
    bind *:80
    default_backend web-backend
backend web-backend
    balance roundrobin
    server web1 15.237.150.77 check
    server web2 13.38.20.126 check
    " > /etc/haproxy/haproxy.cfg
sudo service haproxy restart
