#!/usr/bin/env bash
# blocks all incoming traffic, except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

sudo apt-get install ufw
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
sudo ufw status
